### ISSUE TITLE
Cannot get partition information

### ISSUE THREAD

**Issue by matthias-schlimm** [FSLogix/Invoke-FslShrinkDisk#22]
Testing latest script from 29. September 2020 but got this error in the log 

![image](https://user-images.githubusercontent.com/34108484/94664038-b53a8680-030a-11eb-8d15-4425bdeddbe8.png)

**Comment by JimMoyle** [comment]
Hi Matthias, do you see this on al disks or just these two?

Jim

**Comment by matthias-schlimm** [comment]
Migrated profile from UPM to FSL with this script http://www.citrixirc.com/?p=848 might not be work, I think.

reduce the ThrottleLimit from default to 2 and latest to 1
![image](https://user-images.githubusercontent.com/34108484/94667347-0482b600-030f-11eb-84f1-3ad82dfcb9ce.png)

![image](https://user-images.githubusercontent.com/34108484/94667498-309e3700-030f-11eb-9344-32d844ca66e5.png)

**Comment by sbuck1** [comment]
Hi Jim, hi Matthias,
I could reproduce this behaviour. I also get the same error message when I try to shrink some vhdx files.

Steffen

**Comment by JimMoyle** [comment]
@matthias yes that script creates disks that are a different format to FSLogix created disks and I don't support non-FSLogix disks.

Jim

**Comment by matthias-schlimm** [comment]
I feared that, means creating new vhdx with the frx command and migrate the old data to the new one, to resolve the issue

**Comment by JimMoyle** [comment]
So I have a solution for you, give me a second.

**Comment by JimMoyle** [comment]
run get-partition against the mounted disk you will see the partition has a type that isn't 'Basic' Add that type to the partition check code (search for Basic in the script)

**Comment by JimMoyle** [comment]
It might not work as I have not tested it against non-FSLogix disks, but it will at least not fail the check.

**Comment by matthias-schlimm** [comment]
![image](https://user-images.githubusercontent.com/34108484/94702933-981fab00-033e-11eb-9f9e-0e2f015d9c8d.png)

**Comment by matthias-schlimm** [comment]
if you like I can send you an VHDX with this type IFS for further testing

**Comment by matthias-schlimm** [comment]
I'm looking to the script, where the error "No Partition Supported Size Info - The Windows Disk SubSystem did not respond in a timely fashion try increasing number of cores or decreasing threads by using the ThrottleLimit parameter" is coming from

![image](https://user-images.githubusercontent.com/34108484/94706443-7e806280-0342-11eb-8cdf-66c3cd43973c.png)

**Comment by JimMoyle** [comment]
So I really don't want to start supporting weird partitions, it could get pretty harsh.  I'll take a look at it though.

**Comment by JimMoyle** [comment]
Yeah send me a link and I'll take a look.

**Comment by sbuck1** [comment]
Hi Matthias,
would you like to send me your VHDX file, too?
I had the same error message with native UPD profiles. I replaced 'Basic' with 'IFS' and it worked.

.Steffen

**Comment by matthias-schlimm** [comment]
on a Basic disk I've got the same error

![image](https://user-images.githubusercontent.com/34108484/94772889-ec687080-03ba-11eb-8485-d26d6df9f132.png)

**Starting Shrink via DiskManagement**
![image](https://user-images.githubusercontent.com/34108484/94772916-fbe7b980-03ba-11eb-9665-f3320bb918be.png)

running chkdsk on the attached and afterwards the size can be retrieved **VHDX**
![image](https://user-images.githubusercontent.com/34108484/94772937-0b670280-03bb-11eb-9100-8723d0231e64.png)

**Comment by matthias-schlimm** [comment]
@JimMoyle it works now after running the chkdsk on the vhdx, I think it can be useful to change the text in the message of your script or running an automated chkdsk as well, can be used as an optional parameter like -CheckDisk to perform this operation

**Comment by JimMoyle** [comment]
Thanks Matthias, glad you got it sorted out.

**Comment by ccautaerts** [comment]
Hi Jim & Matthias, 
here is how I 've changed the script, I also used David Ott's script to do the conversion, came across the same issue  but it now works like a charm even with BASIC and IFS partition types, not issues so far.  
Find and replace all lines in the script containing "Where-Object -Property 'Type' -EQ -Value 'Basic'" with "Where-Object { $_.Type -eq "Basic" -or $_.Type -eq "IFS"}  "this way either partition type is OK.
I've also changed the conversion script to use FSLogix FRS.EXE to create new vhdx.
Regards,
Christian
Regards

**Comment by moar1986** [comment]
Hi @ccautaerts, could you please share your modyfied conversion script?

**Comment by ccautaerts** [comment]
Hi,
Please find modified script in attachment. Checkout the comments to adapt to your needs.

Regards,
Christian


Christian Cautaerts | Consultant

Getronics
________________________________
T. +3222299313 | M. +32 477 684 054 | E. Christian.Cautaerts@Getronics.com | W. www.getronics.com
P Please consider the environment before printing this e-mail


Getronics Belgium nv De Kleetlaan 12B, 1831 Diegem,Belgium RPR Brussel/RPM Bruxelles BTW/TVA BE 0424 104 685

The information transmitted is intended only for use by the addressee and may contain confidential and/or privileged material. Any review, retransmission, dissemination or other use of it, or the taking of any action in reliance upon this information by persons and/or entities other than the intended recipient is prohibited. If you received this in error, please inform the sender and/or addressee immediately and delete the material.Please note that this e-mail is also subject to the following disclaimer: http://www.getronics.com/legal/.

**Comment by moar1986** [comment]
@ccautaerts Thank you, just tested the conversion with your script and everything is working fine. Also shrinking is working with Jim's original script.

**Comment by ccautaerts** [comment]
@moar1986. Glad I could help. Jim's script should work as it looks for the BASIC parition type that is created by the FSLogix FRS.EXE.

**Comment by 520958c324** [comment]
@JimMoyle I implemented your advice and changed:

_($allPartition.Type -contains 'Basic')_ **to** _($allPartition.Type -contains 'Basic' -or $allPartition.Type -contains 'IFS')_

and

  _-EQ -Value 'Basic'_  **to**  _-EQ -Value 'Basic' -or -EQ -Value 'IFS'_

And now the script seems to be working fine.

**Comment by gasjur** [comment]
> @ccautaerts Thank you, just tested the conversion with your script and everything is working fine. Also shrinking is working with Jim's original script.

Hi, I tested this script and had the same problem when the vhdx was created with frx.exe. After shrink the profile on the VHDX was corrupt. Only if the VHDX was created via FSLogix, the VHDX is not corrupted during the shrink.
I did further tests and the problem seems to occur only if the script will be launched on Server 2012 R2 but not on Server 2016.

**Comment by ts9999** [comment]
> @JimMoyle I implemented your advice and changed:
> 
> _($allPartition.Type -contains 'Basic')_ **to** _($allPartition.Type -contains 'Basic' -or $allPartition.Type -contains 'IFS')_
> 
> and
> 
> _-EQ -Value 'Basic'_ **to** _-EQ -Value 'Basic' -or -EQ -Value 'IFS'_
> 
> And now the script seems to be working fine.

@520958c324 

I done your amendments to the script, as we migrated user profiles from Persona to FSL using a migration script the file types on the migrated profiles is IFS.

newly created profiles the script acts fine, in our environment it managed to reach around 900 containers, however, we still have around 1200 containers.

The error i get now is:

No Partition Information - The Windows Disk SubSystem did not respond in a timely fashion try increasing number of cores or decreasing threads by using the ThrottleLimit parameter

Wondered if anyone could assist.

@JimMoyle 

Many thanks for the help so far, the script reclaimed around 450GB on our Office Container disk, just need to get these Profile Containers sorted! 

Thanks

**Comment by JimMoyle** [comment]
Hi, 

My tool is intended to be run against FSLogix disks and disks created by any other means are not tested by me and never will be.

However due to the number of people who have used the script you are referencing I've added support for those disks to the next release of the tool which should be available soon depending on my schedule.

Thanks
